#!/bin/bash -il

# Create conda user with the same uid as the host, so the container can write
# to mounted volumes
# Adapted from https://denibertovic.com/posts/handling-permissions-with-docker-volumes/
USER_ID=${HOST_USER_ID:-9001}
useradd --shell /bin/bash -u $USER_ID -o -c "" -m conda
export HOME=/home
export USER=fermi
export LOGNAME=fermi
export MAIL=/var/spool/mail/fermi
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/anaconda/bin
export HEADAS=$HOME/astrosoft/x86_64-unknown-linux-gnu-libc2.12
chown fermi:fermi $HOME
chown -R fermi:fermi /home/anaconda
cp -R /etc/skel $HOME && chown -R fermi:fermi $HOME/skel && (ls -A1 $HOME/skel | xargs -I {} mv -n $HOME/skel/{} $HOME) && rm -Rf $HOME/skel
#cp /root/.condarc $HOME/.condarc && chown conda:conda $HOME/.condarc
cd $HOME

# Source everything that needs to be.
# . /opt/docker/bin/entrypoint_source
. /home/anaconda/bin/activate fermi
. $HEADAS/headas-init.sh

# Run whatever the user wants.
# exec /opt/conda/bin/gosu conda "$@"
