#!/bin/bash -il

# Create conda user with the same uid as the host, so the container can write
# to mounted volumes
# Adapted from https://denibertovic.com/posts/handling-permissions-with-docker-volumes/

USER_ID=${HOST_USER_ID:-9001}
# echo $HOST_USER_ID
# echo $USER_ID
useradd --shell /bin/bash -u $USER_ID -o -c "" -m fermi
usermod -aG root fermi
usermod -aG wheel fermi
echo 'fermi' | passwd fermi --stdin >& /dev/null
export HOME=/home/fermi
export USER=fermi
export LOGNAME=fermi
export MAIL=/var/spool/mail/fermi
export PATH=/opt/anaconda/bin:/home/fermi/astrosoft/tempo/bin:/home/fermi/astrosoft/tempo2/bin
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH
export HEADAS=$HOME/astrosoft/ftools/x86_64-unknown-linux-gnu-libc2.12
export TEMPO2=$HOME/astrosoft/tempo2/T2runtime

## Solve permissions issues
ln -s /home/astrosoft /home/fermi/astrosoft
/opt/anaconda/bin/conda config --add channels conda-forge
chown fermi:fermi $HOME/.condarc
chown fermi:fermi $HOME/astrosoft
chown fermi:fermi $HOME

echo "alias notebook='jupyter notebook --ip 0.0.0.0 --no-browser'" >> $HOME/.bashrc

## I take a long time, only uncomment me if necessary
## |
## V
# chown -R fermi:fermi /opt/anaconda
# chown -R fermi:fermi /home/astrosoft

cd $HOME

# Source everything that needs to be.
. /opt/anaconda/bin/activate fermi
. $HEADAS/headas-init.sh
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/anaconda/envs/fermi/lib
chown -R fermi:fermi $HOME/pfiles

# Run whatever the user wants.
echo "Welcome to the Fermi Container."
exec /opt/anaconda/bin/gosu fermi "$@"
