#!/bin/bash -il

# Create conda user with the same uid as the host, so the container can write
# to mounted volumes
# Adapted from https://denibertovic.com/posts/handling-permissions-with-docker-volumes/

if [ ! -e /.fermibottle ]; then
  touch -d "1 minute ago" /.fermibottle
fi

USER_ID=${HOST_USER_ID:-9001}
# echo $HOST_USER_ID
# echo $USER_ID
useradd --shell /bin/bash -u $USER_ID -o -c "" -m fermi
usermod -aG root fermi
usermod -aG wheel fermi
echo 'fermi' | passwd fermi --stdin >& /dev/null
export HOME=/home/fermi
export USER=fermi
export LOGNAME=fermi
export MAIL=/var/spool/mail/fermi
export ASTROSOFT=$HOME/astrosoft
export PATH=$ASTROSOFT:/opt/anaconda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
export PATH=$ASTROSOFT/bin:/usr/local/bin/rmfit_v432:${PATH}
export PATH=$ASTROSOFT/tempo/bin:$ASTROSOFT/tempo2/bin:$ASTROSOFT/pgplot:$PATH
export HEADAS=$HOME/astrosoft/ftools/x86_64-pc-linux-gnu-libc2.12
export TEMPO2=$HOME/astrosoft/tempo2/T2runtime

## Solve permissions issues
ln -s /home/astrosoft /home/fermi/astrosoft
/opt/anaconda/bin/conda config --add channels conda-forge
/opt/anaconda/bin/conda config --add channels fermi_dev_externals
chown fermi:fermi $HOME/.condarc
chown fermi:fermi $HOME/astrosoft
chown fermi:fermi $HOME
cd $HOME

if [ ! .bash_profile -nt /.fermibottle ]; then
  echo "#################
# Added by entrypoint at date: `date`
# Environment variables
export HOME=${HOME}
export USER=${USER}
export LOGNAME=${LOGNAME}
export MAIL=${MAIL}
export ASTROSOFT=${ASTROSOFT}
export HEADAS=${HEADAS}
export TEMPO2=${TEMPO2}
export PATH=${PATH}:\$PATH

# Source the tools!
. \$HEADAS/headas-init.sh

" >> $HOME/.bash_profile
fi

# Aliases
if [ ! .bashrc -nt /.fermibottle ]; then
  echo "
# Aliases
alias notebook='jupyter notebook --ip 00.00.00.00 --no-browser'
" >> $HOME/.bashrc
fi

# Source everything that needs to be.
. /opt/anaconda/bin/activate fermi
. $HEADAS/headas-init.sh
chown -R fermi:fermi $HOME/pfiles

# Run whatever the user wants.
echo "Welcome to the Fermi Container."
exec /opt/anaconda/bin/gosu fermi "$@"
